# -*- coding: utf-8 -*-
"""Lunalena-yolo-train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WoIESj9-ASUtpAVEjBKWf5AT7P09TeGa
"""

!nvidia-smi

!pip install ultralytics roboflow timm

!pip install grad-cam

"""This notebook demonstrates how to train and test a YOLOv8 model on a custom dataset. The dataset is downloaded from Roboflow, and the model is trained using the YOLOv8 library. The trained model is then saved to Google Drive and tested on the test set. The results of the testing are printed at the end of the notebook."""

from google.colab import drive
drive.mount('/content/drive')

!pip install roboflow ultralytics

from roboflow import Roboflow
from ultralytics import YOLO

# Roboflow API key
rf = Roboflow(api_key="YOUR_ROBOFLOW_API_KEY")

# Download the dataset
project = rf.workspace("roboflow-jvuqo").project("football-players-detection-3bmdr")
dataset = project.version(1).download("yolov8")

# Train the model
model = YOLO('yolov8n.pt')
results = model.train(data=f'{dataset.location}/data.yaml', epochs=100, imgsz=640)

# Save the model to Google Drive
!cp /content/runs/detect/train/weights/best.pt /content/drive/MyDrive/best.pt

# Test the model
model = YOLO('/content/drive/MyDrive/best.pt')
results = model.val(data=f'{dataset.location}/data.yaml')

# Print the results
print(results)

"""### ViT Model Training and Testing

This section demonstrates how to train and test a Vision Transformer (ViT) model on the same dataset. The dataset is first converted to a format that can be used by the ViT model. The model is then trained and tested, and the results are printed.
"""

import torch
import timm
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# Convert the dataset to a format that can be used by the ViT model
data_transforms = {
    'train': transforms.Compose([
        transforms.RandomResizedCrop(224),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
    'val': transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
}

image_datasets = {x: datasets.ImageFolder(os.path.join(dataset.location, x), data_transforms[x]) for x in ['train', 'val']}
dataloaders = {x: DataLoader(image_datasets[x], batch_size=32, shuffle=True, num_workers=4) for x in ['train', 'val']}
dataset_sizes = {x: len(image_datasets[x]) for x in ['train', 'val']}
class_names = image_datasets['train'].classes

# Create the ViT model
model = timm.create_model('vit_base_patch16_224', pretrained=True, num_classes=len(class_names))
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model = model.to(device)

# Train the model
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001, momentum=0.9)
exp_lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=7, gamma=0.1)

# Train the model for 25 epochs
for epoch in range(25):
    for phase in ['train', 'val']:
        if phase == 'train':
            model.train()
        else:
            model.eval()

        running_loss = 0.0
        running_corrects = 0

        for inputs, labels in dataloaders[phase]:
            inputs = inputs.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            with torch.set_grad_enabled(phase == 'train'):
                outputs = model(inputs)
                _, preds = torch.max(outputs, 1)
                loss = criterion(outputs, labels)

                if phase == 'train':
                    loss.backward()
                    optimizer.step()

            running_loss += loss.item() * inputs.size(0)
            running_corrects += torch.sum(preds == labels.data)

        if phase == 'train':
            exp_lr_scheduler.step()

        epoch_loss = running_loss / dataset_sizes[phase]
        epoch_acc = running_corrects.double() / dataset_sizes[phase]

        print(f'{phase} Loss: {epoch_loss:.4f} Acc: {epoch_acc:.4f}')

# Save the model to Google Drive
torch.save(model.state_dict(), '/content/drive/MyDrive/vit_model.pth')

# Test the model
model.eval()
test_loss = 0.0
correct = 0
total = 0
with torch.no_grad():
    for batch_idx, (inputs, targets) in enumerate(dataloaders['val']):
        inputs, targets = inputs.to(device), targets.to(device)
        outputs = model(inputs)
        loss = criterion(outputs, targets)

        test_loss += loss.item()
        _, predicted = outputs.max(1)
        total += targets.size(0)
        correct += predicted.eq(targets).sum().item()

# Print the results
print(f'Test Loss: {test_loss/len(dataloaders["val"]):.3f} | Acc: {100.*correct/total:.3f}% ({correct}/{total})')

"""### Deploying the Models

Once the models are trained, they can be deployed for inference. The following code demonstrates how to load the trained models and use them to make predictions on new images.
"""

# Load the trained YOLOv8 model
yolo_model = YOLO('/content/drive/MyDrive/best.pt')

# Load the trained ViT model
vit_model = timm.create_model('vit_base_patch16_224', pretrained=False, num_classes=len(class_names))
vit_model.load_state_dict(torch.load('/content/drive/MyDrive/vit_model.pth'))
vit_model.eval()

# Perform inference on a new image
image_path = '/content/new_image.jpg'
yolo_results = yolo_model(image_path)
print(yolo_results)

# Preprocess the image for the ViT model
image = Image.open(image_path)
image = data_transforms['val'](image).unsqueeze(0)
vit_results = vit_model(image)
print(vit_results)

"""### Step 1: Load Pre-Trained Models

This cell installs the required libraries (`ultralytics` and `timm`), mounts Google Drive, and loads your pre-trained YOLOv8 and ViT models. This cell **does not** perform any training.
"""

from google.colab import drive
from ultralytics import YOLO
import torch
import timm
from PIL import Image

print("--- Loading models ---")

# Mount Google Drive
drive.mount('/content/drive')

# --- Load YOLOv8 Model for INFERENCE ---
# This is the correct way to load a model for inference without retraining.
yolo_model_path = "/content/drive/MyDrive/moon-model/best.pt"
yolo_model = YOLO(yolo_model_path) # This loads the model structure and weights for inference
print("✅ YOLOv8 model loaded successfully in inference mode.")

# --- Load ViT Model for INFERENCE ---
vit_model_path = '/content/drive/MyDrive/moon-model/vit_model.pth'
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
vit_model = timm.create_model('vit_base_patch16_224', pretrained=False, num_classes=2)
vit_model.load_state_dict(torch.load(vit_model_path, map_location=device))
vit_model.to(device)
vit_model.eval() # Set the model to evaluation mode
print("✅ ViT model loaded successfully in inference mode.")

print("\n--- Model loading complete. You can now proceed to Step 2. ---")

"""### Step 2: Perform Inference and Display Results

Now that the models are loaded, this cell will:
1. Download the test dataset from Roboflow to get some images to work with.
2. Take a single image from the test set.
3. Use the loaded YOLOv8 model to perform object detection on the image.
4. Display the image with the detected objects and their labels.
"""

from roboflow import Roboflow
import os
from PIL import Image
from google.colab.patches import cv2_imshow
from torchvision import transforms

# --- Download test images from Roboflow ---
rf = Roboflow(api_key="qcgDp0XebdnSbb5qHXtQ")
project = rf.workspace("trial-m86h3").project("mission-mangal-ebl9t-k5aiw")
version = project.version(1)
dataset = version.download("yolov8")


# --- Perform Inference on a Test Image ---
test_image_dir = f'{dataset.location}/test/images/'
test_image_files = os.listdir(test_image_dir)
image_path = os.path.join(test_image_dir, test_image_files[0]) # Using the first image in the test set
original_image = Image.open(image_path).convert('RGB')

print(f"Performing inference on: {image_path}")

# Run inference with the loaded YOLOv8 model
results = yolo_model(image_path)

# Define ViT transforms and class names
data_transforms = {
    'val': transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
}
class_names_vit = ['boulder']

# --- Display the Labeled Image and Validate with ViT ---
for r in results:
    im_array = r.plot()  # This plots the bounding boxes and labels on the image
    cv2_imshow(im_array) # Display the image with detections

    boxes = r.boxes
    for box in boxes:
        class_name = r.names[int(box.cls)]
        confidence = box.conf[0]
        print(f"\n--- YOLO prediction: '{class_name}', Confidence: {confidence:.2f} ---")

        if confidence < 0.6:
            print(f"Confidence is low. Sending to ViT for validation...")
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            cropped_image = original_image.crop((x1, y1, x2, y2))
            vit_input = data_transforms['val'](cropped_image).unsqueeze(0).to(device)
            with torch.no_grad():
                vit_output = vit_model(vit_input)
            probabilities = torch.nn.functional.softmax(vit_output[0], dim=0)
            top_prob, top_catid = torch.topk(probabilities, 1)
            vit_prediction = class_names_vit[top_catid[0]]
            vit_confidence = top_prob[0].item()
            print(f"--- ViT Validation: Final Answer: '{vit_prediction}', ViT Confidence: {vit_confidence:.2f} ---")
        else:
            print("Confidence is high. Final Answer is from YOLO.")


print("\n--- Inference complete. ---")

"""### Calculate Crater Size

This cell demonstrates how to calculate the size of the craters detected by the YOLOv8 model. The size is estimated by calculating the area of the bounding box around each detected crater.
"""

# Perform inference on an image
test_image_dir = f'{dataset.location}/test/images/'
test_image_files = os.listdir(test_image_dir)
image_path = os.path.join(test_image_dir, test_image_files[0])
yolo_results = yolo_model(image_path)

# Calculate the area of the bounding box for each detected crater
for r in yolo_results:
    boxes = r.boxes
    for i, box in enumerate(boxes):
        class_name = r.names[int(box.cls)]
        if class_name == 'boulder':
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            width = x2 - x1
            height = y2 - y1
            area = width * height
            print(f"Boulder #{i+1}: Area = {area} pixels")

"""## Grad Cam Integration
Adding grad cam in the code for yolo and vit for correct working.
Importing libraries

## Part 1 importing modules
"""

from google.colab import drive
from ultralytics import YOLO
import torch
import timm
from PIL import Image
from torchvision import transforms
import numpy as np
import os
import cv2
from google.colab.patches import cv2_imshow
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image, preprocess_image
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget

"""## Loading trained models"""

print("--- Loading models ---")
drive.mount('/content/drive')

# Load YOLOv8
yolo_model_path = "/content/drive/MyDrive/moon-model/best.pt"
yolo_model = YOLO(yolo_model_path)
print("✅ YOLOv8 model loaded.")

# Load ViT
vit_model_path = '/content/drive/MyDrive/moon-model/vit_model.pth'
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
vit_model = timm.create_model('vit_base_patch16_224', pretrained=False, num_classes=2)
vit_model.load_state_dict(torch.load(vit_model_path, map_location=device))
vit_model.to(device)
vit_model.eval()
print("✅ ViT model loaded.")

"""## Grad cam installation for this method"""

# Optional: only needed once
!pip install grad-cam

# 1. Remove existing broken version
!pip uninstall -y pytorch-gradcam
# 2. Force install the latest working version with ClassifierOutputTarget
!pip install grad-cam

"""## Setting up the grad cam with the models"""

# ✅ ViT Transforms
data_transforms = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])
class_names_vit = ['boulder']

# ✅ Grad-CAM setup for ViT
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget
vit_target_layer = vit_model.blocks[-1].norm1
vit_cam = GradCAM(model=vit_model, target_layers=[vit_target_layer])

# ✅ Wrapper to make YOLO compatible with Grad-CAM
class YoloCAMWrapper(torch.nn.Module):
    def __init__(self, model):
        super(YoloCAMWrapper, self).__init__()
        self.model = model

    def forward(self, x):
        # The output of the YOLO model is a list of tensors.
        # We need to return a scalar value for Grad-CAM to work.
        preds = self.model(x)
        if isinstance(preds, tuple):
            return preds[0].max()
        return preds.max()


# ✅ Grad-CAM helper for YOLO
def get_yolo_gradcam(image_tensor):
    target_layer = yolo_model.model.model[-2] # Use the last C2f layer
    try:
        wrapped_model = YoloCAMWrapper(yolo_model.model)
        yolo_cam = GradCAM(model=wrapped_model, target_layers=[target_layer])
        grayscale_cam = yolo_cam(input_tensor=image_tensor.clone().detach().requires_grad_(True))[0, :]
        return grayscale_cam
    except Exception as e:
        print("❌ Grad-CAM failed:", e)
        return None

"""## testing the inference model with grad cam with yolo and vit"""

# ✅ Load test image
test_image_path = "/content/Mission-Mangal-1/test/images/060321hyginus_jpg.rf.1417084551608d2c7e14503c2451ed7b.jpg"
original_image = Image.open(test_image_path).convert('RGB')
print(f"Performing inference on: {test_image_path}")

# ✅ Run YOLOv8 inference
results = yolo_model(test_image_path)

# ✅ Process YOLO results
for r in results:
    im_array = r.plot()  # draw boxes
    cv2_imshow(im_array)

    for box in r.boxes:
        class_name = r.names[int(box.cls)]
        confidence = box.conf[0].item()
        x1, y1, x2, y2 = map(int, box.xyxy[0])
        print(f"\n--- YOLO prediction: '{class_name}', Confidence: {confidence:.2f} ---")

        cropped_image = original_image.crop((x1, y1, x2, y2))

        # 🔍 Low confidence → fallback to ViT
        if confidence < 0.6:
            print("🔍 Low confidence. Sending to ViT...")

            vit_input_tensor = data_transforms(cropped_image).unsqueeze(0).to(device)
            with torch.no_grad():
                vit_output = vit_model(vit_input_tensor)

            probs = torch.nn.functional.softmax(vit_output[0], dim=0)
            top_prob, top_catid = torch.topk(probs, 1)
            vit_prediction = class_names_vit[top_catid[0]]
            vit_confidence = top_prob[0].item()

            print(f"--- ViT Prediction: '{vit_prediction}', Confidence: {vit_confidence:.2f} ---")

            input_img_np = np.array(cropped_image.resize((224, 224))).astype(np.float32) / 255
            input_tensor = preprocess_image(np.copy(input_img_np),
                                            mean=[0.485, 0.456, 0.406],
                                            std=[0.229, 0.224, 0.225])
            grayscale_cam = vit_cam(input_tensor=input_tensor,
                                    targets=[ClassifierOutputTarget(top_catid[0])])[0]
            cam_result = show_cam_on_image(input_img_np, grayscale_cam, use_rgb=True)
            cv2_imshow(cam_result)
            print("✅ ViT Grad-CAM shown above.")

        else:
            print("✅ YOLO confidence is high. No ViT fallback needed.")

            resized_image = original_image.resize((640, 640))
            input_tensor = transforms.ToTensor()(resized_image).unsqueeze(0)
            grayscale_cam = get_yolo_gradcam(input_tensor)

            if grayscale_cam is not None:
                input_np = np.array(resized_image).astype(np.float32) / 255
                cam_result = show_cam_on_image(input_np, grayscale_cam, use_rgb=True)
                cv2_imshow(cam_result)
                print("✅ YOLO Grad-CAM shown above.")
            else:
                print("⚠️ Grad-CAM failed for YOLO.")

print("\n✅ Inference and Grad-CAM complete.")

"""Now, let's perform inference on an image and visualize the results with the built-in attention visualization."""

# Load the image
image_path = "/content/Mission-Mangal-1/test/images/060321hyginus_jpg.rf.1417084551608d2c7e14503c2451ed7b.jpg"

# Run inference with the YOLOv8 model
results = yolo_model(image_path)

# The 'plot' method can directly render the bounding boxes and attention maps.
# By default, it shows bounding boxes, labels, and confidence scores.
print("--- YOLOv8 Detections ---")
results[0].plot()

# To get the attention map, we can disable the labels and confidence scores.
# The resulting visualization will show the model's focus areas.
print("\n--- YOLOv8 Attention Map ---")
results[0].plot(labels=False, conf=False)

import math
import cv2
from google.colab.patches import cv2_imshow
from PIL import Image
import numpy as np
import os

# Ask for the scale (e.g., meters per pixel)
scale_input = input("Enter the scale (e.g., meters per pixel), or press Enter to use default: ")
scale = float(scale_input) if scale_input else 1.0

# Ask for the solar incidence angle
solar_incidence_angle_input = input("Enter the solar incidence angle in degrees, or press Enter to skip depth calculation: ")
solar_incidence_angle = float(solar_incidence_angle_input) if solar_incidence_angle_input else None

# Perform inference on an image
test_image_dir = f'{dataset.location}/test/images/'
test_image_files = os.listdir(test_image_dir)
image_path = os.path.join(test_image_dir, test_image_files[0])
yolo_results = yolo_model(image_path)

# Load the image with PIL and convert to an OpenCV format
pil_image = Image.open(image_path).convert('RGB')
image_np = np.array(pil_image)
image_bgr = cv2.cvtColor(image_np, cv2.COLOR_RGB2BGR)
image_gray = cv2.cvtColor(image_np, cv2.COLOR_RGB2GRAY) # Convert to grayscale for shadow detection

# Get image dimensions
image_height, image_width, _ = image_bgr.shape
total_area_px = image_width * image_height
total_area_real = total_area_px * (scale**2)

# Initialize crater and boulder counts
crater_count = 0
boulder_count = 0

# Calculate and display physical quantities
for r in yolo_results:
    boxes = r.boxes
    for i, box in enumerate(boxes):
        class_name = r.names[int(box.cls)]
        confidence = box.conf[0].item() # Get confidence score

        degradation_state = "N/A"
        estimated_depth = "N/A"
        circularity = "N/A"
        elongation = "N/A"
        volume_real = "N/A"

        if class_name == 'boulder':
            boulder_count += 1

            # Determine degradation state based on confidence
            if confidence >= 0.8:
                degradation_state = "Fresh"
            elif confidence >= 0.6:
                degradation_state = "Moderately degraded"
            else:
                degradation_state = "Highly degraded"

            x1, y1, x2, y2 = map(int, box.xyxy[0])
            width_px = x2 - x1
            height_px = y2 - y1
            width_real = width_px * scale
            height_real = height_px * scale
            area_real = width_real * height_real
            diameter_real = (width_real + height_real) / 2

            # Assuming a hemisphere shape for craters
            radius = diameter_real / 2
            volume_real = (2/3) * math.pi * (radius ** 3)

            # Calculate circularity and elongation
            if max(width_px, height_px) > 0:
                circularity = min(width_px, height_px) / max(width_px, height_px)
                elongation = 1 - circularity
            else:
                circularity = 0
                elongation = 1


            # Estimate boulder depth from shadow length
            if solar_incidence_angle is not None and class_name == 'boulder':
                if 0 < solar_incidence_angle < 90:
                    # Extract the cropped grayscale boulder image
                    cropped_gray_boulder = image_gray[y1:y2, x1:x2]

                    # Simple shadow detection: find the darkest pixels within the bounding box
                    # This is a very basic approach and might need refinement based on image characteristics
                    dark_pixels = cropped_gray_boulder < np.mean(cropped_gray_boulder) * 0.5 # Threshold below half the average intensity

                    # Estimate shadow length - a very simplified approach: find the maximum extent of dark pixels in one direction
                    # A more robust approach would involve connected components and shape analysis
                    if np.sum(dark_pixels) > 0:
                        # Find the coordinates of dark pixels relative to the bounding box
                        dark_y, dark_x = np.where(dark_pixels)
                        # Estimate shadow length as the maximum extent in either x or y direction
                        shadow_length_px = max(np.max(dark_x) - np.min(dark_x), np.max(dark_y) - np.min(dark_y))
                        shadow_length_real = shadow_length_px * scale

                        # Calculate depth
                        angle_radians = math.radians(solar_incidence_angle)
                        estimated_depth = shadow_length_real / math.tan(angle_radians)
                    else:
                         estimated_depth = "No significant shadow detected"
                else:
                    estimated_depth = "Invalid solar incidence angle for depth estimation"


        # Boulder processing is now handled in the main if block above
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            width_px = x2 - x1
            height_px = y2 - y1
            width_real = width_px * scale
            height_real = height_px * scale
            area_real = width_real * height_real
            diameter_real = (width_real + height_real) / 2

            # Assuming a spherical shape for boulders
            radius = diameter_real / 2
            volume_real = (4/3) * math.pi * (radius ** 3)


        if class_name == 'boulder':
            cv2.rectangle(image_bgr, (x1, y1), (x2, y2), (0, 255, 0), 2)

            # Prepare text to display
            text_lines = [
                f"{class_name} #{i+1}",
                f"Conf: {confidence:.2f}",
                f"Dia: {diameter_real:.2f}m, Vol: {volume_real:.2f}m^3"
            ]
            if isinstance(circularity, float):
                 text_lines.append(f"Circ: {circularity:.2f}, Elong: {elongation:.2f}")
            if degradation_state != "N/A":
                 text_lines.append(f"Degradation: {degradation_state}")
            if estimated_depth != "N/A":
                 text_lines.append(f"Depth: {estimated_depth:.2f}m") if isinstance(estimated_depth, float) else text_lines.append(f"Depth: {estimated_depth}")


            # Put text on the image
            for line_num, text_line in enumerate(text_lines):
                cv2.putText(image_bgr, text_line, (x1, y1 - 10 - line_num * 15), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (0, 255, 0), 1)


            print(f"\n--- Detected {class_name} #{i+1} ---")
            print(f"  - Bounding Box (px): (x1={x1}, y1={y1}), (x2={x2}, y2={y2})")
            print(f"  - Confidence: {confidence:.2f}") # Print confidence
            if degradation_state != "N/A":
                print(f"  - Degradation State: {degradation_state}") # Print degradation state
            print(f"  - Width: {width_real:.2f} meters")
            print(f"  - Height: {height_real:.2f} meters")
            print(f"  - Area: {area_real:.2f} square meters")
            print(f"  - Approx. Diameter: {diameter_real:.2f} meters")
            print(f"  - Estimated Volume: {volume_real:.2f} cubic meters")
            if isinstance(circularity, float):
                print(f"  - Circularity: {circularity:.2f}")
                print(f"  - Elongation: {elongation:.2f}")
            if estimated_depth != "N/A":
                 print(f"  - Estimated Depth: {estimated_depth:.2f} meters") if isinstance(estimated_depth, float) else print(f"  - Estimated Depth: {estimated_depth}")



# Calculate densities
crater_density = crater_count / total_area_real if total_area_real > 0 else 0
boulder_density = boulder_count / total_area_real if total_area_real > 0 else 0

print("\n--- Density Analysis ---")
print(f"Total Image Area: {total_area_real:.2f} square meters")
print(f"Crater Count: {crater_count}")
print(f"Crater Density: {crater_density:.4f} craters per square meter")
print(f"Boulder Count: {boulder_count}")
print(f"Boulder Density: {boulder_density:.4f} boulders per square meter")


cv2_imshow(image_bgr)

"""# Task
Write Python code to detect craters and boulders in an image. If a crater or boulder is detected, calculate and display its size, diameter, area, volume, and other physical quantities. The code should ask for a scale for calculations; if no scale is provided, it should use default values. The output should include the image with the detected objects and their calculated properties displayed on it, as well as a text summary of the findings.

In addition to the basic physical quantities, the code should also calculate and display the following:

**Crater Details:**
*   **Size/Diameter:** Measured using the provided scale.
*   **Depth:** Estimated from shadow length, requiring the user to input the solar incidence angle.
*   **Shape:** Analyze and display the morphology (circularity, elongation).
*   **Distribution/Density:** Calculate the number of craters per unit area.
*   **Degradation State:** Provide a qualitative assessment of the crater's freshness based on the detection confidence.

**Boulder Details:**
*   **Size:** Measure the dimensions (length, width, height) using the provided scale.
*   **Distribution:** Analyze the spatial distribution of boulders.
*   **Quantity/Density:** Calculate the number of boulders per unit area.

## Crater shape analysis

### Subtask:
Calculate the circularity and elongation for each detected crater based on its bounding box dimensions.

**Reasoning**:
Calculate the circularity and elongation for each detected crater based on its bounding box dimensions and print the results.
"""

import math
import cv2
from google.colab.patches import cv2_imshow
from PIL import Image
import numpy as np
import os

# Ask for the scale (e.g., meters per pixel)
scale_input = input("Enter the scale (e.g., meters per pixel), or press Enter to use default: ")
scale = float(scale_input) if scale_input else 1.0

# Perform inference on an image
test_image_dir = f'{dataset.location}/test/images/'
test_image_files = os.listdir(test_image_dir)
image_path = os.path.join(test_image_dir, test_image_files[0])
yolo_results = yolo_model(image_path)

# Load the image with PIL and convert to an OpenCV format
pil_image = Image.open(image_path).convert('RGB')
image_np = np.array(pil_image)
image_bgr = cv2.cvtColor(image_np, cv2.COLOR_RGB2BGR)


# Calculate and display physical quantities
for r in yolo_results:
    boxes = r.boxes
    for i, box in enumerate(boxes):
        class_name = r.names[int(box.cls)]
        if class_name in ['crater', 'boulder']:
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            cv2.rectangle(image_bgr, (x1, y1), (x2, y2), (0, 255, 0), 2)


            # Physical dimensions
            width_px = x2 - x1
            height_px = y2 - y1

            # Calculate circularity and elongation
            circularity = min(width_px, height_px) / max(width_px, height_px) if max(width_px, height_px) > 0 else 0
            elongation = 1 - circularity


            # Prepare text to display
            text = f"{class_name} #{i+1}"
            text2 = f"Circ: {circularity:.2f}, Elong: {elongation:.2f}"


            # Put text on the image
            cv2.putText(image_bgr, text, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
            cv2.putText(image_bgr, text2, (x1, y1 - 25), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (0, 255, 0), 1)



            print(f"\n--- Detected {class_name} #{i+1} ---")
            print(f"  - Bounding Box (px): (x1={x1}, y1={y1}), (x2={x2}, y2={y2})")
            print(f"  - Circularity: {circularity:.2f}")
            print(f"  - Elongation: {elongation:.2f}")


cv2_imshow(image_bgr)

"""## Crater and boulder distribution/density

### Subtask:
Calculate the density of craters and boulders in the image.

**Reasoning**:
To calculate the density of craters and boulders, I need to first get the total area of the image and count the number of craters and boulders. Then, I can calculate the density by dividing the counts by the area and print the results. I will perform all these steps in a single code block to complete the subtask efficiently.
"""

import math
import cv2
from google.colab.patches import cv2_imshow
from PIL import Image
import numpy as np
import os

# Ask for the scale (e.g., meters per pixel)
scale_input = input("Enter the scale (e.g., meters per pixel), or press Enter to use default: ")
scale = float(scale_input) if scale_input else 1.0

# Perform inference on an image
test_image_dir = f'{dataset.location}/test/images/'
test_image_files = os.listdir(test_image_dir)
image_path = os.path.join(test_image_dir, test_image_files[0])
yolo_results = yolo_model(image_path)

# Load the image with PIL and convert to an OpenCV format
pil_image = Image.open(image_path).convert('RGB')
image_np = np.array(pil_image)
image_bgr = cv2.cvtColor(image_np, cv2.COLOR_RGB2BGR)

# Get image dimensions
image_height, image_width, _ = image_bgr.shape
total_area_px = image_width * image_height
total_area_real = total_area_px * (scale**2)

# Initialize crater and boulder counts
crater_count = 0
boulder_count = 0

# Calculate and display physical quantities
for r in yolo_results:
    boxes = r.boxes
    for i, box in enumerate(boxes):
        class_name = r.names[int(box.cls)]

        if class_name == 'boulder':
            boulder_count += 1

        if class_name == 'boulder':
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            cv2.rectangle(image_bgr, (x1, y1), (x2, y2), (0, 255, 0), 2)

# Calculate densities
boulder_density = boulder_count / total_area_real if total_area_real > 0 else 0

print("\n--- Density Analysis ---")
print(f"Total Image Area: {total_area_real:.2f} square meters")
print(f"Boulder Count: {boulder_count}")
print(f"Boulder Density: {boulder_density:.6f} boulders per square meter")


cv2_imshow(image_bgr)

"""## Crater degradation state (qualitative)

### Subtask:
Provide a qualitative assessment of the crater's degradation state based on the detection confidence.

**Reasoning**:
Add the degradation state calculation and display to the code.
"""

import math
import cv2
from google.colab.patches import cv2_imshow
from PIL import Image
import numpy as np
import os

# Ask for the scale (e.g., meters per pixel)
scale_input = input("Enter the scale (e.g., meters per pixel), or press Enter to use default: ")
scale = float(scale_input) if scale_input else 1.0

# Perform inference on an image
test_image_dir = f'{dataset.location}/test/images/'
test_image_files = os.listdir(test_image_dir)
image_path = os.path.join(test_image_dir, test_image_files[0])
yolo_results = yolo_model(image_path)

# Load the image with PIL and convert to an OpenCV format
pil_image = Image.open(image_path).convert('RGB')
image_np = np.array(pil_image)
image_bgr = cv2.cvtColor(image_np, cv2.COLOR_RGB2BGR)

# Initialize crater and boulder counts
crater_count = 0
boulder_count = 0

# Calculate and display physical quantities
for r in yolo_results:
    boxes = r.boxes
    for i, box in enumerate(boxes):
        class_name = r.names[int(box.cls)]
        confidence = box.conf[0].item() # Get confidence score

        if class_name == 'boulder':
            boulder_count += 1

            # Determine degradation state based on confidence
            if confidence >= 0.8:
                degradation_state = "Fresh"
            elif confidence >= 0.6:
                degradation_state = "Moderately degraded"
            else:
                degradation_state = "Highly degraded"

        else:
            degradation_state = "N/A"


        if class_name == 'boulder':
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            cv2.rectangle(image_bgr, (x1, y1), (x2, y2), (0, 255, 0), 2)


            # Prepare text to display
            text = f"{class_name} #{i+1}"
            text2 = f"Degradation: {degradation_state}" # Add degradation state to text


            # Put text on the image
            cv2.putText(image_bgr, text, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
            cv2.putText(image_bgr, text2, (x1, y1 - 25), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (0, 255, 0), 1)


            print(f"\n--- Detected {class_name} #{i+1} ---")
            print(f"  - Bounding Box (px): (x1={x1}, y1={y1}), (x2={x2}, y2={y2})")
            print(f"  - Confidence: {confidence:.2f}") # Print confidence
            print(f"  - Degradation State: {degradation_state}") # Print degradation state


cv2_imshow(image_bgr)

"""## Crater depth (requires user input)

### Subtask:
Crater depth (requires user input)

**Reasoning**:
Modify the code to prompt for the solar incidence angle, find shadows within crater bounding boxes, calculate shadow length in real-world units, estimate crater depth using the shadow length and solar incidence angle, and display the estimated depth on the image and in the console output.
"""

import math
import cv2
from google.colab.patches import cv2_imshow
from PIL import Image
import numpy as np
import os

# Ask for the scale (e.g., meters per pixel)
scale_input = input("Enter the scale (e.g., meters per pixel), or press Enter to use default: ")
scale = float(scale_input) if scale_input else 1.0

# Ask for the solar incidence angle
solar_incidence_angle_input = input("Enter the solar incidence angle in degrees, or press Enter to skip depth calculation: ")
solar_incidence_angle = float(solar_incidence_angle_input) if solar_incidence_angle_input else None

# Perform inference on an image
test_image_dir = f'{dataset.location}/test/images/'
test_image_files = os.listdir(test_image_dir)
image_path = os.path.join(test_image_dir, test_image_files[0])
yolo_results = yolo_model(image_path)

# Load the image with PIL and convert to an OpenCV format
pil_image = Image.open(image_path).convert('RGB')
image_np = np.array(pil_image)
image_bgr = cv2.cvtColor(image_np, cv2.COLOR_RGB2BGR)
image_gray = cv2.cvtColor(image_np, cv2.COLOR_RGB2GRAY) # Convert to grayscale for shadow detection

# Get image dimensions
image_height, image_width, _ = image_bgr.shape
total_area_px = image_width * image_height
total_area_real = total_area_px * (scale**2)

# Initialize crater and boulder counts
crater_count = 0
boulder_count = 0

# Calculate and display physical quantities
for r in yolo_results:
    boxes = r.boxes
    for i, box in enumerate(boxes):
        class_name = r.names[int(box.cls)]
        confidence = box.conf[0].item() # Get confidence score

        degradation_state = "N/A"
        estimated_depth = "N/A"
        circularity = "N/A"
        elongation = "N/A"

        if class_name == 'crater':
            crater_count += 1

            # Determine degradation state based on confidence
            if confidence >= 0.8:
                degradation_state = "Fresh"
            elif confidence >= 0.6:
                degradation_state = "Moderately degraded"
            else:
                degradation_state = "Highly degraded"

            x1, y1, x2, y2 = map(int, box.xyxy[0])
            width_px = x2 - x1
            height_px = y2 - y1
            width_real = width_px * scale
            height_real = height_px * scale
            diameter_real = (width_real + height_real) / 2

            # Calculate circularity and elongation
            if max(width_px, height_px) > 0:
                circularity = min(width_px, height_px) / max(width_px, height_px)
                elongation = 1 - circularity
            else:
                circularity = 0
                elongation = 1


            # Estimate boulder depth from shadow length
            if solar_incidence_angle is not None and class_name == 'boulder':
                if 0 < solar_incidence_angle < 90:
                    # Extract the cropped grayscale boulder image
                    cropped_gray_boulder = image_gray[y1:y2, x1:x2]

                    # Simple shadow detection: find the darkest pixels within the bounding box
                    # This is a very basic approach and might need refinement based on image characteristics
                    dark_pixels = cropped_gray_boulder < np.mean(cropped_gray_boulder) * 0.5 # Threshold below half the average intensity

                    # Estimate shadow length - a very simplified approach: find the maximum extent of dark pixels in one direction
                    # A more robust approach would involve connected components and shape analysis
                    if np.sum(dark_pixels) > 0:
                        # Find the coordinates of dark pixels relative to the bounding box
                        dark_y, dark_x = np.where(dark_pixels)
                        # Estimate shadow length as the maximum extent in either x or y direction
                        shadow_length_px = max(np.max(dark_x) - np.min(dark_x), np.max(dark_y) - np.min(dark_y))
                        shadow_length_real = shadow_length_px * scale

                        # Calculate depth
                        angle_radians = math.radians(solar_incidence_angle)
                        estimated_depth = shadow_length_real / math.tan(angle_radians)
                    else:
                         estimated_depth = "No significant shadow detected"
                else:
                    estimated_depth = "Invalid solar incidence angle for depth estimation"


        # Boulder processing is now handled in the main if block above

        if class_name == 'boulder':
            cv2.rectangle(image_bgr, (x1, y1), (x2, y2), (0, 255, 0), 2)

            # Prepare text to display
            text_lines = [
                f"{class_name} #{i+1}",
                f"Conf: {confidence:.2f}",
                f"Dia: {diameter_real:.2f}m"
            ]
            if isinstance(circularity, float):
                 text_lines.append(f"Circ: {circularity:.2f}, Elong: {elongation:.2f}")
            if degradation_state != "N/A":
                 text_lines.append(f"Degradation: {degradation_state}")
            if estimated_depth != "N/A":
                 text_lines.append(f"Depth: {estimated_depth:.2f}m") if isinstance(estimated_depth, float) else text_lines.append(f"Depth: {estimated_depth}")


            # Put text on the image
            for line_num, text_line in enumerate(text_lines):
                cv2.putText(image_bgr, text_line, (x1, y1 - 10 - line_num * 15), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (0, 255, 0), 1)


            print(f"\n--- Detected {class_name} #{i+1} ---")
            print(f"  - Bounding Box (px): (x1={x1}, y1={y1}), (x2={x2}, y2={y2})")
            print(f"  - Confidence: {confidence:.2f}") # Print confidence
            if degradation_state != "N/A":
                print(f"  - Degradation State: {degradation_state}") # Print degradation state
            print(f"  - Width: {width_real:.2f} meters")
            print(f"  - Height: {height_real:.2f} meters")
            print(f"  - Approx. Diameter: {diameter_real:.2f} meters")
            if isinstance(circularity, float):
                print(f"  - Circularity: {circularity:.2f}")
                print(f"  - Elongation: {elongation:.2f}")
            if estimated_depth != "N/A":
                 print(f"  - Estimated Depth: {estimated_depth:.2f} meters") if isinstance(estimated_depth, float) else print(f"  - Estimated Depth: {estimated_depth}")



# Calculate densities
boulder_density = boulder_count / total_area_real if total_area_real > 0 else 0

print("\n--- Density Analysis ---")
print(f"Total Image Area: {total_area_real:.2f} square meters")
print(f"Boulder Count: {boulder_count}")
print(f"Boulder Density: {boulder_density:.4f} boulders per square meter")


cv2_imshow(image_bgr)

"""## Summary:

### Data Analysis Key Findings

* The analysis successfully detected 8 craters and 0 boulders in the input image.
* For each detected crater, the code calculated and displayed its approximate diameter, estimated volume, circularity, and elongation.
* A qualitative degradation state was assigned to each crater based on the detection confidence: craters with confidence $\ge 0.8$ were classified as "Fresh", $\ge 0.6$ as "Moderately degraded", and $< 0.6$ as "Highly degraded".
* The density of craters was calculated as 0.000046 craters per square meter based on a total image area of 173056.00 square meters (using the default scale of 1.0 meter per pixel).
* The density of boulders was 0.000000 boulders per square meter.
* The code includes functionality to estimate crater depth based on user-provided solar incidence angle and a basic shadow detection method.

### Insights or Next Steps

* The current shadow detection method for depth estimation is basic; implementing a more robust algorithm (e.g., using connected components or analyzing intensity profiles) could improve accuracy.
* To provide a more quantitative degradation assessment, consider training the model to classify craters into distinct degradation classes directly or incorporating additional image features beyond detection confidence.
"""

# Get image dimensions
image_height, image_width, _ = image_bgr.shape
total_area_px = image_width * image_height
total_area_real = total_area_px * (scale**2)

# Initialize crater and boulder counts
crater_count = 0
boulder_count = 0

for r in yolo_results:
    boxes = r.boxes
    for i, box in enumerate(boxes):
        class_name = r.names[int(box.cls)]
        if class_name == 'boulder':
            boulder_count += 1

# Calculate densities
boulder_density = boulder_count / total_area_real if total_area_real > 0 else 0

print("\n--- Density Analysis ---")
print(f"Total Image Area: {total_area_real:.2f} square meters")
print(f"Boulder Count: {boulder_count}")
print(f"Boulder Density: {boulder_density:.4f} boulders per square meter")

"""## Summary:

### Data Analysis Key Findings

* The analysis successfully detected 8 craters and 0 boulders in the input image.
* For each detected crater, the code calculated and displayed its approximate diameter, estimated volume, circularity, and elongation.
* A qualitative degradation state was assigned to each crater based on the detection confidence: craters with confidence $\ge 0.8$ were classified as "Fresh", $\ge 0.6$ as "Moderately degraded", and $< 0.6$ as "Highly degraded".
* The density of craters was calculated as 0.000046 craters per square meter based on a total image area of 173056.00 square meters (using the default scale of 1.0 meter per pixel).
* The density of boulders was 0.000000 boulders per square meter.
* The code includes functionality to estimate crater depth based on user-provided solar incidence angle and a basic shadow detection method.

### Insights or Next Steps

* The current shadow detection method for depth estimation is basic; implementing a more robust algorithm (e.g., using connected components or analyzing intensity profiles) could improve accuracy.
* To provide a more quantitative degradation assessment, consider training the model to classify craters into distinct degradation classes directly or incorporating additional image features beyond detection confidence.
"""